import Foundation

/// Why a copy was not kept. Worth naming rather than returning a bare `false`:
/// "nothing appeared in my clipboard history" is otherwise unfalsifiable, and
/// the settings pane can show the last reason.
public enum ClipboardSkipReason: Equatable, Sendable {
    /// Marked by the copying app as never-store. Honoured unconditionally.
    case markedPrivate(String)
    case ignoredType(String)
    case ignoredApp(String)
    case empty
    case unsupported
    /// Too big to be worth keeping — see `ClipboardLimits`.
    case tooLarge(bytes: Int)
}

public extension ClipboardSkipReason {
    /// Why the copy was not kept, as words — the half after "Last copy
    /// skipped:" in Settings.
    ///
    /// **Never the pasteboard type.** This used to read "marked private
    /// (org.nspasteboard.ConcealedType)", which is a sentence about a string;
    /// the type stays in the enum, for the classifier and its tests.
    /// `appName` turns a bundle identifier into the app's name, which only the
    /// app target can do.
    func words(appName: (String) -> String) -> String {
        switch self {
        case .markedPrivate: return "the app it came from marked it private"
        case .ignoredType: return "it came from a password manager"
        case .ignoredApp(let bundle): return "it came from \(appName(bundle)), which is never recorded"
        case .empty: return "there was nothing in it to keep"
        case .unsupported: return "it wasn't text, a picture or a file"
        case .tooLarge(let bytes):
            return "it was too large to keep (\(ClipboardLimits.describe(bytes: bytes)))"
        }
    }

    /// What the clipboard tab says after a copy too large to keep — otherwise
    /// the copy simply never appears, and the notch says nothing about why.
    static func tooLargeNotice(bytes: Int) -> String {
        "The last thing you copied was too large to keep (\(ClipboardLimits.describe(bytes: bytes))). "
            + "It's still on the clipboard, just not in the history."
    }
}

public enum ClipboardDecision: Equatable, Sendable {
    case takeText
    case takeImage
    case takeFile
    case skip(ClipboardSkipReason)
}

/// Decides whether a pasteboard change is ours to keep.
///
/// Pure: it is handed the type identifiers and the source app, never an
/// `NSPasteboard`. That is what makes the privacy rules — the part of this
/// feature where a bug means storing a password — testable without a running
/// pasteboard.
public struct PasteboardClassifier: Equatable, Sendable {
    /// The cross-app convention for "do not put this in a clipboard manager".
    /// Password managers and 2FA apps set these, and no setting may turn them
    /// off — a user cannot consent on behalf of the app that marked it.
    public static let alwaysIgnoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Vendor-specific markers, removable in settings. These are apps that
    /// predate the convention above or use their own flavour of it.
    public static let defaultIgnoredTypes: Set<String> = [
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
        "Pasteboard generator type",
    ]

    /// Password managers that do not mark their pasteboard at all. Ignoring the
    /// app is the only defence left in that case.
    public static let defaultIgnoredApps: Set<String> = [
        "com.apple.keychainaccess",
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.dashlane.Dashlane",
        "in.sinew.Enpass-Desktop",
        "com.lastpass.LastPass",
    ]

    public static let textTypes: Set<String> = [
        "public.utf8-plain-text",
        "public.plain-text",
        "NSStringPboardType",
    ]

    public static let fileTypes: Set<String> = [
        "public.file-url",
    ]

    public static let imageTypes: Set<String> = [
        "public.png",
        "public.tiff",
        "public.jpeg",
        "com.compuserve.gif",
    ]

    public var ignoredTypes: Set<String>
    public var ignoredApps: Set<String>

    public init(ignoredTypes: Set<String> = defaultIgnoredTypes,
                ignoredApps: Set<String> = defaultIgnoredApps) {
        self.ignoredTypes = ignoredTypes
        self.ignoredApps = ignoredApps
    }

    /// Order matters and is safety-first, the same shape as the policy engine:
    /// unconditional privacy markers, then configurable ignores, then content.
    /// Any reordering that let content win would be a leak.
    public func decide(types: [String], sourceBundleID: String? = nil) -> ClipboardDecision {
        for type in types where Self.alwaysIgnoredTypes.contains(type) {
            return .skip(.markedPrivate(type))
        }
        for type in types where ignoredTypes.contains(type) {
            return .skip(.ignoredType(type))
        }
        if let bundleID = sourceBundleID, ignoredApps.contains(bundleID) {
            return .skip(.ignoredApp(bundleID))
        }
        // A file URL wins over both, and it has to: Finder puts the path on the
        // pasteboard as text alongside the file reference, so under the
        // text-first rule below every file you copied was recorded as a string
        // of its own path. The browser argument for text-over-image does not
        // apply here — nothing offers `public.file-url` for a text selection.
        if types.contains(where: Self.fileTypes.contains) { return .takeFile }
        // Text wins over image when both are present. Copying from a browser
        // offers HTML, RTF, image and plain text at once, and the plain text is
        // what you actually wanted to paste.
        if types.contains(where: Self.textTypes.contains) { return .takeText }
        if types.contains(where: Self.imageTypes.contains) { return .takeImage }
        return .skip(.unsupported)
    }
}
